apiVersion: v1
kind: Service
metadata:
  name: motando-moto-svc
spec:
  selector:
    api: moto    
    rel: beta
    ver: "20220304"
    env: prod    
  ports:
    - port: 5000
      targetPort: moto-port
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moto-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:  
  rules:
  - http:
      paths:
        - path: /moto/marca
          pathType: Prefix
          backend:
            service:
              name: motando-moto-svc
              port:
                number: 5000        
        - path: /moto/marca/[0-9]{3}
          pathType: Prefix
          backend:
            service:
              name: motando-moto-svc
              port:
                number: 5000     
        - path: /moto/marca/[0-9]{3}/modelo
          pathType: Prefix
          backend:
            service:
              name: motando-moto-svc
              port:
                number: 5000   
        - path: /moto/marca/[0-9]{3}/modelo/[0-9]{3}
          pathType: Prefix
          backend:
            service:
              name: motando-moto-svc
              port:
                number: 5000       
        - path: /moto/marca/[0-9]{3}/modelo/[0-9]{3}/versao
          pathType: Prefix
          backend:
            service:
              name: motando-moto-svc
              port:
                number: 5000       
        - path: /moto/marca/[0-9]{3}/modelo/[0-9]{3}/versao/[0-9]{3}
          pathType: Prefix
          backend:
            service:
              name: motando-moto-svc
              port:
                number: 5000       