apiVersion: v1
kind: Pod
metadata:
  name: motando-usuario
  labels:
    api: usuario    
    rel: beta
    ver: "20220304"
    env: prod    
spec:
  containers:
  - name: usuario-crt
    image: gru.ocir.io/idreywyoj0pu/motando-api-usuario:latest
    ports:
      - containerPort: 5000
        name: usuario-port
    env:
        - name: MOTANDO_BUCKET_NAME
          value: motando_usuario
        - name: MOTANDO_NOSQL_TABLE_NAME
          value: motando_usuario
    envFrom:
        - prefix: MOTANDO_
          configMapRef:
              name: motando-config
  imagePullSecrets:
       - name: motando-secret