apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:     
      app: motando-frontend
      rel: beta
      ver: "1.0"
  ports:      
    - port: 80
      targetPort: nginx-port      
      nodePort: 30080