apiVersion: v1
kind: Pod
metadata:
  name: motando-auth
  labels:
    api: auth    
    rel: beta
    ver: "20220304"
    env: prod    
spec:
  containers:
  - name: auth-crt
    image: gru.ocir.io/idreywyoj0pu/motando-api-auth:latest
    ports:
      - containerPort: 5000
        name: auth-port
    env:    
        - name: MOTANDO_NOSQL_SESSAO_TABLE_NAME
          value: motando_sessao
        - name: MOTANDO_NOSQL_USUARIO_TABLE_NAME
          value: motando_usuario
    envFrom:
        - prefix: MOTANDO_
          configMapRef:
              name: motando-config
  imagePullSecrets:
       - name: motando-secret